### ISSUE TITLE
Help for start...

### ISSUE THREAD

**Issue by GevaudanBeast** [PLCHome/velux-klf200#1]
Hello,
I'm trying to find out if I can use your work with ha-bridge to pilot my somfy rolling shutters?
Do you have examples of practical use because I do not understand how to make it work?

**Comment by PLCHome** [comment]
The KLF-200 is a hardware gateway from Velux© to control io-homecontrol© parts. 
[As it apparently also Somfy io-homecontrol © devices.](http://www.io-homecontrol.com/index.php/de/die-markenhersteller/somfy)
 Should it be possible for these in the KLF-200 to create a scene. If that is possible you can control the devices

You are here in the second part of the project:

Api:
[velux-klf200-api](https://github.com/PLCHome/velux-klf200-api)
Middleware:
[velux-klf200](https://github.com/PLCHome/velux-klf200)
Node-Red:
[node-red-contrib-velux](https://github.com/PLCHome/node-red-contrib-velux)

The easiest way to connect habridge is via MQTT with Node-Red.
If you want to program: could the choice on mqtt or own rest api

With the habridge I only have troubles I'm just replacing them with a node-red implementation. The main problem is that you can not pass the device state to the habridge.

However you need a KLF-200
